import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import PrimeVue from "primevue/config";
import Toolbar from "primevue/toolbar";
import Button from "primevue/button";
import SplitButton from "primevue/splitbutton";
import Sidebar from "primevue/sidebar";
import Avatar from "primevue/avatar";
import PanelMenu from "primevue/panelmenu";
import FileUpload from "primevue/fileupload";
import Menubar from "primevue/menubar";
import Chart from "primevue/chart";
import Splitter from "primevue/splitter";
import SplitterPanel from "primevue/splitterpanel";
import Card from "primevue/card";
import Divider from "primevue/divider";
import InputText from "primevue/inputtext";
import Checkbox from "primevue/checkbox";
import Dropdown from "primevue/dropdown";
import Password from "primevue/password";
import Dialog from "primevue/dialog";
import BlockUI from "primevue/blockui";
import Toast from "primevue/toast";
import ToastService from "primevue/toastservice";
import ProgressSpinner from "primevue/progressspinner";
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import ColumnGroup from "primevue/columngroup";

import "primevue/resources/themes/vela-blue/theme.css";
import "primevue/resources/primevue.min.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";

const app = createApp(App);
app.use(PrimeVue, { ripple: true });
app.use(store);
app.use(router);
app.use(ToastService);

app.component("Toolbar", Toolbar);
app.component("Button", Button);
app.component("SplitButton", SplitButton);
app.component("Sidebar", Sidebar);
app.component("FileUpload", FileUpload);
app.component("Menubar", Menubar);
app.component("PanelMenu", PanelMenu);
app.component("Avatar", Avatar);
app.component("Chart", Chart);
app.component("Card", Card);
app.component("Splitter", Splitter);
app.component("SplitterPanel", SplitterPanel);
app.component("Divider", Divider);
app.component("InputText", InputText);
app.component("Checkbox", Checkbox);
app.component("Dropdown", Dropdown);
app.component("Password", Password);
app.component("Dialog", Dialog);
app.component("BlockUI", BlockUI);
app.component("Toast", Toast);
app.component("ProgressSpinner", ProgressSpinner);
app.component("DataTable", DataTable);
app.component("Column", Column);
app.component("ColumnGroup", ColumnGroup);

app.mount("#app");
